var annotated_dup =
[
    [ "juce", "namespacejuce.html", [
      [ "AccessibilityHandler", null, [
        [ "AccessibilityNativeImpl", "classjuce_1_1_accessibility_handler_1_1_accessibility_native_impl.html", "classjuce_1_1_accessibility_handler_1_1_accessibility_native_impl" ]
      ] ],
      [ "CustomMouseCursorInfo", "structjuce_1_1_custom_mouse_cursor_info.html", "structjuce_1_1_custom_mouse_cursor_info" ],
      [ "macPasteboard", "classjuce_1_1mac_pasteboard.html", "classjuce_1_1mac_pasteboard" ],
      [ "StandaloneFilterWindow", "classjuce_1_1_standalone_filter_window.html", "classjuce_1_1_standalone_filter_window" ],
      [ "StandalonePluginHolder", "classjuce_1_1_standalone_plugin_holder.html", "classjuce_1_1_standalone_plugin_holder" ]
    ] ],
    [ "AdsrEnvelope", "class_adsr_envelope.html", "class_adsr_envelope" ],
    [ "ApInterpolator", "class_ap_interpolator.html", "class_ap_interpolator" ],
    [ "ButtonList", "class_button_list.html", "class_button_list" ],
    [ "CustomLabel", "class_custom_label.html", "class_custom_label" ],
    [ "CustomLookAndFeel", "class_custom_look_and_feel.html", "class_custom_look_and_feel" ],
    [ "Decimator17", "class_decimator17.html", "class_decimator17" ],
    [ "Decimator9", "class_decimator9.html", "class_decimator9" ],
    [ "DelayLine", "class_delay_line.html", "class_delay_line" ],
    [ "DelayLineBoolean", "class_delay_line_boolean.html", "class_delay_line_boolean" ],
    [ "Filter", "class_filter.html", "class_filter" ],
    [ "fxChunkSet", "structfx_chunk_set.html", "structfx_chunk_set" ],
    [ "fxProgram", "structfx_program.html", "structfx_program" ],
    [ "fxProgramSet", "structfx_program_set.html", "structfx_program_set" ],
    [ "fxSet", "structfx_set.html", "structfx_set" ],
    [ "ImageMenu", "class_image_menu.html", "class_image_menu" ],
    [ "Knob", "class_knob.html", "class_knob" ],
    [ "KnobLookAndFeel", "class_knob_look_and_feel.html", "class_knob_look_and_feel" ],
    [ "Lfo", "class_lfo.html", "class_lfo" ],
    [ "MidiMap", "class_midi_map.html", "class_midi_map" ],
    [ "Motherboard", "class_motherboard.html", "class_motherboard" ],
    [ "MTSClient", "struct_m_t_s_client.html", "struct_m_t_s_client" ],
    [ "mtsclientglobal", "structmtsclientglobal.html", "structmtsclientglobal" ],
    [ "ObxdAudioProcessor", "class_obxd_audio_processor.html", "class_obxd_audio_processor" ],
    [ "ObxdAudioProcessorEditor", "class_obxd_audio_processor_editor.html", "class_obxd_audio_processor_editor" ],
    [ "ObxdBank", "class_obxd_bank.html", "class_obxd_bank" ],
    [ "ObxdOscillatorB", "class_obxd_oscillator_b.html", "class_obxd_oscillator_b" ],
    [ "ObxdParams", "class_obxd_params.html", "class_obxd_params" ],
    [ "ObxdVoice", "class_obxd_voice.html", "class_obxd_voice" ],
    [ "ParamSmoother", "class_param_smoother.html", "class_param_smoother" ],
    [ "PresetBar", "class_preset_bar.html", "class_preset_bar" ],
    [ "PulseOsc", "class_pulse_osc.html", "class_pulse_osc" ],
    [ "SawOsc", "class_saw_osc.html", "class_saw_osc" ],
    [ "ScalableComponent", "class_scalable_component.html", "class_scalable_component" ],
    [ "SetPresetNameWindow", "class_set_preset_name_window.html", "class_set_preset_name_window" ],
    [ "SynthEngine", "class_synth_engine.html", "class_synth_engine" ],
    [ "TooglableButton", "class_tooglable_button.html", "class_tooglable_button" ],
    [ "TriangleOsc", "class_triangle_osc.html", "class_triangle_osc" ],
    [ "Tuning", "class_tuning.html", "class_tuning" ],
    [ "VoiceQueue", "class_voice_queue.html", "class_voice_queue" ]
];